project:
  type: website
  output-dir: docs
  resources:
    - "files/"
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!renv/"
    - "!certificate*"

website:
  favicon: files/logo.jpg
  google-analytics: "G-DSTHFZLFYC"
  title: "Fredd Villabona"
  navbar:
      logo: /files/logo.jpg
      background: "#09213e"
      right:
      - href: index.qmd
        text: 🏠 Home
      - programandoenr.qmd
#      - ca.qmd
      - notes.qmd

  
#page-footer: "Built with Quarto - 2023"

  page-footer:
    left: |
      Built with Quarto
#    center: 
#      - icon: github
#        href: https://github.com/willingc
#      - icon: linkedin
#        href: https://www.linkedin.com/in/carolwilling/
#      - icon: twitter
#        href: https://twitter.com/WillingCarol
#      - icon: rss
#        href: index.xml
    right: |
      2025

format:
  html-lumo:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


