project:
  type: website
  output-dir: docs

website:
  title: "Freddy Villabona"
  page-footer: "Built with Quarto - 2023"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - programandoenr.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


